sudo: required
dist: trusty
language: java
jdk:
  - oraclejdk8

language: ruby
rvm: 2.2

cache:
  directories:
  - $HOME/.m2
  - grakn-dashboard/node_modules
  - grakn-engine/npm

notifications:
  slack: grakn:RbxoPzX267spGT4cgmoGLMpT
  email: false
  
install: mvn install -T 2.5C -DskipTests=true -Dmaven.javadoc.skip=true -B -V

jobs:
  include:
    # run tests with maven
    # Split tests into grakn-test and everything else
    - script: scripts/test.sh  "grakn-test/test-integration" Test
    - script: scripts/test.sh  "grakn-test/test-integration" IT
    - script: scripts/test.sh "!grakn-test/test-integration" Test
    - script: scripts/test.sh "!grakn-test/test-integration" IT

    # test docs
    - script: scripts/test-docs.sh


before_install:
  - npm config set registry http://registry.npmjs.org/
