################################################################################
#
# Travis CI is used to run Grakn tests on Tinkerpop graph, as opposed to Janus
#
################################################################################

sudo: required
dist: trusty
language: java
jdk:
  - openjdk8 

cache:
  directories:
  - $HOME/.m2
  - grakn-dashboard/node_modules
  - grakn-engine/npm

env:
  # Split tests into grakn-test and everything else
  - TESTS=**/*Test* MODULE=grakn-test/test-integration
  - TESTS=**/*IT*   MODULE=grakn-test/test-integration
  - TESTS=**/*Test* MODULE=!grakn-test/test-integration
  - TESTS=**/*IT*   MODULE=!grakn-test/test-integration

before_install:
  - npm config set registry http://registry.npmjs.org/

install: mvn install -T 2.5C -DskipTests=true -Dmaven.javadoc.skip=true -B -V

# https://docs.travis-ci.com/user/build-stages/#How-to-define-Build-Stages%3F
jobs:
  include:
    - stage: test
      script: mvn test -P tinker --projects "$MODULE" -Dtest=$TESTS -DfailIfNoTests=false -Dsurefire.rerunFailingTestsCount=1 jacoco:report
    - stage: deploy
      if: type IN (push, cron, api)
      script:
        - mvn sonar:sonar

addons:
  sonarcloud:
    organization: "grakn-labs"
    branches:
      - master
      - stable

notifications:
  slack: grakn:RbxoPzX267spGT4cgmoGLMpT
  email: false