sudo: required
dist: trusty
language: java
jdk:
  - oraclejdk8
cache:
  directories:
  - $HOME/.m2
notifications:
  slack: grakn:RbxoPzX267spGT4cgmoGLMpT
script:
    - mvn test
before_install:
  - sudo apt-get -y install npm
  - npm install -g npm
