sudo: required
dist: trusty
language: java
jdk:
  - oraclejdk8

language: node_js
node_js:
  - "6"

language: ruby
rvm: 2.2

cache:
   directories:
   - $HOME/.m2
   - grakn-dashboard/node_modules
   - grakn-engine/npm

notifications:
  slack: grakn:RbxoPzX267spGT4cgmoGLMpT
  email: false
  
install: mvn install -T 2.5C -DskipTests=true -Dmaven.javadoc.skip=true -B -V

jobs:
  include:

    # run tests with maven
    - script:
        - mvn test --projects "$MODULE" -Dtest=$TESTS -DfailIfNoTests=false jacoco:report
        - bash <(curl -s https://codecov.io/bash)
      env:
        # Split tests into grakn-test and everything else
        - TESTS=**/*Test* MODULE=grakn-test/test-integration
        - TESTS=**/*IT*   MODULE=grakn-test/test-integration
        - TESTS=**/*Test* MODULE=!grakn-test/test-integration
        - TESTS=**/*IT*   MODULE=!grakn-test/test-integration

    # test docs
    - script:
        - cd docs
        - rake test


before_install:
  - npm config set registry http://registry.npmjs.org/