sudo: required
dist: trusty
language: java
jdk:
  - oraclejdk8

cache:
   directories:
   - $HOME/.m2
   - grakn-dashboard/node_modules

notifications:
  slack: grakn:RbxoPzX267spGT4cgmoGLMpT
install: mvn install -T 2.5C -DskipTests=true -Dmaven.javadoc.skip=true -Dmaven.wagon.http.ssl.allowall=true -B -V
script:
    - mvn test jacoco:report -Dmaven.wagon.http.ssl.allowall=true
    - bash <(curl -s https://codecov.io/bash)
before_install:
  - npm install -g npm
