sudo: required
dist: trusty
language: java
jdk:
  - oraclejdk8

language: node_js
node_js:
  - "6"

cache:
   directories:
   - $HOME/.m2
   - grakn-dashboard/node_modules
   - grakn-engine/npm

env:
  - TESTS=**/*Test* MODULE=grakn-dashboard
  - TESTS=**/*IT*   MODULE=grakn-dashboard
  - TESTS=**/*Test* MODULE=grakn-dist
  - TESTS=**/*IT*   MODULE=grakn-dist
  - TESTS=**/*Test* MODULE=grakn-engine
  - TESTS=**/*IT*   MODULE=grakn-engine
  - TESTS=**/*Test* MODULE=grakn-factory
  - TESTS=**/*IT*   MODULE=grakn-factory
  - TESTS=**/*Test* MODULE=grakn-graph
  - TESTS=**/*IT*   MODULE=grakn-graph
  - TESTS=**/*Test* MODULE=grakn-graql
  - TESTS=**/*IT*   MODULE=grakn-graql
  - TESTS=**/*Test* MODULE=grakn-graql-shell
  - TESTS=**/*IT*   MODULE=grakn-graql-shell
  - TESTS=**/*Test* MODULE=grakn-migration
  - TESTS=**/*IT*   MODULE=grakn-migration
  - TESTS=**/*Test* MODULE=grakn-test
  - TESTS=**/*IT*   MODULE=grakn-test

notifications:
  slack: grakn:RbxoPzX267spGT4cgmoGLMpT
  email: false
  
install: mvn install -T 2.5C -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
    - mvn test -pl $MODULE -Dtest=$TESTS -DfailIfNoTests=false jacoco:report
    - bash <(curl -s https://codecov.io/bash)
before_install:
  - npm config set registry http://registry.npmjs.org/