sudo: required
dist: trusty
language: java
jdk:
  - oraclejdk8
notifications:
  slack: grakn:RbxoPzX267spGT4cgmoGLMpT
script:
    - mvn test jacoco:report coveralls:report
before_install:
  - sudo apt-get -y install npm
  - npm install -g npm
