sudo: required
dist: trusty
language: java
jdk:
  - oraclejdk8

cache:
   directories:
   - $HOME/.m2
   - grakn-dashboard/node_modules
   - grakn-engine/npm

env:
  - TESTS=**/*Test*
  - TESTS=**/*IT*

notifications:
  slack: grakn:RbxoPzX267spGT4cgmoGLMpT
install: mvn install -T 2.5C -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
    - mvn test -Dtest=$TESTS -DfailIfNoTests=false jacoco:report
    - bash <(curl -s https://codecov.io/bash)
before_install:
  - npm config set registry http://registry.npmjs.org/
  - npm install -g npm
