name: "societal model"
schema: "societal_model/societal_model.gql"
queries: "societal_model/queries.yml"
concepts:
  - 100
  - 250
  - 500
repeatsPerQuery: 5
# TODO
# concurrency:
#   clients: 1
  # mixed:
# replication: 1

