name: "societal model"
schema: "/grakn-benchmark/src/main/resources/societal_model/societal_model.gql"
queries: "/grakn-benchmark/src/main/resources/societal_model/queries.yml"
concepts:
  - 100
  - 250
  - 500
# concurrency:
#   clients: 1
  # mixed:
# replication: 1

