version: 2.1
commands:
  rbe_install_credential:
    description: Remote Build Execution - Install Google Cloud Credential
    steps:
      - run: |
          if [[ -n "$GOOGLE_CLOUD_REMOTE_BUILD_EXECUTION_CREDENTIAL" ]]; then
            mkdir -p ~/.config/gcloud/
            echo $GOOGLE_CLOUD_REMOTE_BUILD_EXECUTION_CREDENTIAL > ~/.config/gcloud/application_default_credentials.json
          fi
references:
  install_bazel: &install_bazel
    run:
      name: Install bazel
      command: |
        curl -OL https://github.com/bazelbuild/bazel/releases/download/0.20.0/bazel-0.20.0-installer-linux-x86_64.sh
        chmod +x bazel-0.20.0-installer-linux-x86_64.sh
        sudo ./bazel-0.20.0-installer-linux-x86_64.sh

  attach_grakn_workspace: &attach_grakn_workspace
    attach_workspace:
      at: ~/grakn

jobs:
  build:
    machine: true
    working_directory: ~/grakn
    steps:
      - checkout
      - *install_bazel
      - rbe_install_credential
      - run: python ./check-for-missing-checkstyle-rule.py
      - run: bazel build //... --sandbox_debug --config=rbe
      - run: mkdir dist/ && mv bazel-genfiles/grakn-core-all.zip dist/
      - persist_to_workspace: #share Grakn with other jobs by putting it in the workspace
          root: ~/grakn
          paths:
            - .

  client-java:
    machine: true
    working_directory: ~/grakn
    steps:
    - checkout
    - *install_bazel
    - rbe_install_credential
    - run: bazel test //client-java/... --test_size_filters=small --test_output=errors --config=rbe
    - run: bazel test //client-java/... --test_size_filters=medium,large,enormous --test_output=errors --config=rbe

  client-nodejs:
    machine: true
    working_directory: ~/grakn
    steps:
    - checkout
    - *install_bazel
    - rbe_install_credential
    - run: bazel build //:distribution --sandbox_debug
    - run: unzip bazel-genfiles/grakn-core-all.zip -d bazel-genfiles/dist/
    - run: nohup bazel-genfiles/dist/grakn server start
    - run: bazel-genfiles/dist/grakn console -f `pwd`/test-end-to-end/test-fixtures/basic-genealogy.gql -k gene
    - run: bazel test //client-nodejs:test-integration --test_output=streamed

  client-python:
    machine: true
    working_directory: ~/grakn
    steps:
    - checkout
    - *install_bazel
    - rbe_install_credential
    - run: bazel build //:distribution --sandbox_debug
    - run: unzip bazel-genfiles/grakn-core-all.zip -d bazel-genfiles/dist/
    - run: nohup bazel-genfiles/dist/grakn server start
    - run: bazel test //client_python:test_integration --test_output=streamed

  common:
    machine: true
    working_directory: ~/grakn
    steps:
    - checkout
    - *install_bazel
    - rbe_install_credential
    - run: bazel test //common/... --test_output=errors --config=rbe

  console:
    machine: true
    working_directory: ~/grakn
    steps:
      - checkout
      - *install_bazel
      - rbe_install_credential
      - run: bazel test //console/... --test_output=errors --config=rbe

  graql:
    machine: true
    working_directory: ~/grakn
    steps:
    - checkout
    - *install_bazel
    - rbe_install_credential
    - run: bazel test //graql/... --test_output=errors --config=rbe

  server:
    machine: true
    working_directory: ~/grakn
    steps:
    - checkout
    - *install_bazel
    - rbe_install_credential
    - run: bazel test //server/... --test_output=errors --config=rbe

  workbase:
    machine: true
    working_directory: ~/grakn
    steps:
    - checkout
    - *install_bazel
    - rbe_install_credential
    - run: bazel test //workbase:tests-unit --test_output=errors --config=rbe
    - run: sudo apt install xvfb libxtst6 libxss1 libgtk2.0-0 -y
    - run: sudo apt install libnss3 libasound2 libgconf-2-4 -y
    - run: bazel build //:distribution --sandbox_debug --config=rbe
    - run: unzip bazel-genfiles/grakn-core-all.zip -d bazel-genfiles/dist/
    - run: nohup bazel-genfiles/dist/grakn server start
    - run: bazel-genfiles/dist/grakn console -f `pwd`/test-end-to-end/test-fixtures/basic-genealogy.gql -k gene
    - run: Xvfb :99 &
    - run: export DISPLAY=:99
    - run: bazel test //workbase:tests-e2e --test_output=streamed --config=rbe

  test-integration:
    machine: true
    working_directory: ~/grakn
    steps:
      - checkout
      - *install_bazel
      - rbe_install_credential
      - run: bazel test //test-integration/server/... --test_output=errors --config=rbe
      - run: bazel test //test-integration/graql/internal/... --test_output=errors --config=rbe
      - run: bazel test //test-integration/graql/query/... --test_output=errors --config=rbe

  test-integration-reasoner:
    machine: true
    working_directory: ~/grakn
    steps:
    - checkout
    - *install_bazel
    - rbe_install_credential
    - run: bazel test //test-integration/graql/reasoner:reasoning-it --test_output=errors --config=rbe
    - run: bazel test //test-integration/graql/reasoner:geo-inference-it --test_output=errors --config=rbe

  test-integration-reasoner-general:
    machine: true
    working_directory: ~/grakn
    steps:
    - checkout
    - *install_bazel
    - rbe_install_credential
    - run: bazel test //test-integration/graql/reasoner/reasoning/... --test_output=errors --config=rbe

  test-integration-reasoner-components:
    machine: true
    working_directory: ~/grakn
    steps:
    - checkout
    - *install_bazel
    - rbe_install_credential
    - run: bazel test //test-integration/graql/reasoner/atomic/... --test_output=errors --config=rbe
    - run: bazel test //test-integration/graql/reasoner/benchmark/... --test_output=errors --config=rbe
    - run: bazel test //test-integration/graql/reasoner/cache/... --test_output=errors --config=rbe
    - run: bazel test //test-integration/graql/reasoner/query/... --test_output=errors --config=rbe

  test-integration-analytics:
    machine: true
    working_directory: ~/grakn
    steps:
    - checkout
    - *install_bazel
    - rbe_install_credential
    - run: bazel test //test-integration/graql/analytics/... --test_output=errors --config=rbe

  test-end-to-end:
    machine: true
    working_directory: ~/grakn
    steps:
      - checkout
      - *install_bazel
      - rbe_install_credential
      - run: bazel build //:distribution --sandbox_debug --config=rbe
      - run: bazel test //test-end-to-end:test-end-to-end --test_output=streamed --spawn_strategy=standalone --config=rbe

  build-workbase-linux:
      machine: true
      working_directory: ~/grakn
      steps:
        - *attach_grakn_workspace
        - run: bazel run @nodejs//:npm install
        - run: bazel build //workbase:distribution --config=rbe
        - run: echo 'export GRAKN_VERSION=$(echo ${CIRCLE_TAG} | cut -c 2-)' >> $BASH_ENV #remove 'v' from tag name and use it as Grakn Version to be released
        # FIXME: make a separate rule for building on Linux / use another naming scheme
        - run: mv ./bazel-genfiles/workbase/grakn-workbase.zip ~/grakn/artifacts/grakn-workbase-${GRAKN_VERSION}-linux.tar.gz
        - persist_to_workspace:
            root: ~/grakn
            paths:
              - artifacts/*-linux.tar.gz

  build-workbase-mac:
      macos:
          xcode: "9.0"
      working_directory: ~/grakn
      steps:
        - *attach_grakn_workspace
        - run: echo 'export GRAKN_VERSION=$(echo ${CIRCLE_TAG} | cut -c 2-)' >> $BASH_ENV #remove 'v' from tag name and use it as Grakn Version to be released
        - run: unzip artifacts/grakn-core-${GRAKN_VERSION}.zip
        - run: cd grakn-core-${GRAKN_VERSION} && nohup ./grakn server start
        - run: cd grakn-core-${GRAKN_VERSION} && ./graql console -f ./examples/basic-genealogy.gql -k gene
        - run: bazel run @nodejs//:npm install
        - run: bazel test //workbase:tests-e2e --test_output=errors --config=rbe
        - run: bazel build //workbase:distribution --config=rbe
        - run: mv ./bazel-genfiles/workbase/grakn-workbase.zip ~/grakn/artifacts/grakn-workbase-${GRAKN_VERSION}-mac.zip
        - persist_to_workspace:
            root: ~/grakn
            paths:
              - artifacts/*-mac.zip

  publish-github-draft:
    docker:
      - image: cibuilds/github:0.10
    working_directory: ~/grakn
    steps:
      - attach_workspace:
          at: ~/grakn
      - run:
          name: "Publish Draft Release on GitHub"
          command: |
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete -draft ${CIRCLE_TAG} ./artifacts

  grakn-release-build:
    machine: true
    working_directory: ~/grakn
    steps:
      - checkout
      - *install_bazel
      - run: echo 'export GRAKN_VERSION=$(echo ${CIRCLE_TAG} | cut -c 2-)' >> $BASH_ENV #remove 'v' from tag name and use it as Grakn Version to be released
      - run: mvn --batch-mode install -T 2.5C -DskipTests=true
      - run: mkdir ~/grakn/artifacts
      - run: mv grakn-dist/target/grakn-core-${GRAKN_VERSION}.zip ~/grakn/artifacts
      - persist_to_workspace: #share Grakn with other jobs by putting it in the workspace
          root: ~/grakn
          paths:
            - ./artifacts
            - ./workbase

workflows:
  version: 2
  grakn-core-ci:
    jobs:
      - build
      - client-java
      - client-nodejs
      - client-python
      - common
      - console
      - graql
      - server
      - workbase
      - test-integration
      - test-integration-reasoner
      - test-integration-reasoner-general
      - test-integration-reasoner-components
      - test-integration-analytics
      - test-end-to-end

  build-and-deploy:
    jobs:
      - grakn-release-build:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - build-workbase-mac:
          requires:
             - grakn-release-build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - build-workbase-linux:
          requires:
             - grakn-release-build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - publish-github-draft:
          requires:
            - build-workbase-mac
            - build-workbase-linux
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
