version: 2.1
commands:
  bazel_install:
    steps:
      - run:
          name: Bazel - Install
          command: |
            curl -OL https://github.com/bazelbuild/bazel/releases/download/0.20.0/bazel-0.20.0-installer-linux-x86_64.sh
            chmod +x bazel-0.20.0-installer-linux-x86_64.sh
            sudo ./bazel-0.20.0-installer-linux-x86_64.sh
  bazel_add_rbe_credential:
    steps:
      - run:
          name: Bazel - Add RBE Credential
          command: |
            if [[ -n "$BAZEL_RBE_CREDENTIAL" ]]; then
              BAZEL_RBE_CREDENTIAL_LOCATION=~/.config/gcloud/application_default_credentials.json
              echo "An RBE credential is found and will be saved to $BAZEL_RBE_CREDENTIAL_LOCATION. Bazel will be executed with RBE support."
              mkdir -p ~/.config/gcloud/
              echo $BAZEL_RBE_CREDENTIAL > "$BAZEL_RBE_CREDENTIAL_LOCATION"
            else
              echo "No RBE credential found. Bazel will be executed locally without RBE support."
            fi
  bazel:
    parameters:
      command:
          type: string
    steps:
      - run:
          name: Bazel - Execute
          command: |
            if [[ -f ~/.config/gcloud/application_default_credentials.json ]]; then
              echo "Bazel will be executed with RBE support. This means the build is remotely executed and the cache will be re-used by subsequent CI jobs."
              CMD="<< parameters.command >> --config=rbe"
            else
              echo "Bazel will be executed locally (without RBE support)."
              CMD="<< parameters.command >>"
            fi
            echo "Executing $CMD"
            $CMD
  rpm_install:
    steps:
      - run:
          name: Install rpm (for rpmbuild)
          command: sudo apt update && sudo apt install rpm -y

jobs:
  build:
    machine: true
    working_directory: ~/grakn
    steps:
      - checkout
      - bazel_install
      - bazel_add_rbe_credential
      - run: python ./check-for-missing-checkstyle-rule.py
      - rpm_install
      - bazel:
          command: bazel build //...
      - run: mkdir dist/ && mv bazel-genfiles/grakn-core-all.zip dist/
      - persist_to_workspace: # TODO: share Grakn with other jobs by putting it in the workspace
          root: ~/grakn
          paths:
            - .

  client-java:
    machine: true
    working_directory: ~/grakn
    steps:
      - checkout
      - bazel_install
      - bazel_add_rbe_credential
      - bazel:
          command: bazel test //client-java/... --test_size_filters=small --test_output=errors
      - bazel:
          command: bazel test //client-java/... --test_size_filters=medium,large,enormous --test_output=errors

  common:
    machine: true
    working_directory: ~/grakn
    steps:
      - checkout
      - bazel_install
      - bazel_add_rbe_credential
      - bazel:
          command: bazel test //common/... --test_output=errors

  console:
    machine: true
    working_directory: ~/grakn
    steps:
      - checkout
      - bazel_install
      - bazel_add_rbe_credential
      - rpm_install
      - bazel:
          command: bazel test //console/... --test_output=errors

  graql:
    machine: true
    working_directory: ~/grakn
    steps:
      - checkout
      - bazel_install
      - bazel_add_rbe_credential
      - bazel:
          command: bazel test //graql/... --test_output=errors

  server:
    machine: true
    working_directory: ~/grakn
    steps:
      - checkout
      - bazel_install
      - bazel_add_rbe_credential
      - rpm_install
      - bazel:
          command: bazel test //server/... --test_output=errors

  test-integration:
    machine: true
    working_directory: ~/grakn
    steps:
      - checkout
      - bazel_install
      - bazel_add_rbe_credential
      - bazel:
          command: bazel test //test-integration/server/... --test_output=errors
      - bazel:
          command: bazel test //test-integration/graql/internal/... --test_output=errors
      - bazel:
          command: bazel test //test-integration/graql/query/... --test_output=errors

  test-integration-reasoner:
    machine: true
    working_directory: ~/grakn
    steps:
    - checkout
    - bazel_install
    - bazel_add_rbe_credential
    - bazel:
        command: bazel test //test-integration/graql/reasoner/... --test_output=errors

  test-integration-analytics:
    machine: true
    working_directory: ~/grakn
    steps:
    - checkout
    - bazel_install
    - bazel_add_rbe_credential
    - bazel:
        command: bazel test //test-integration/graql/analytics/... --test_output=errors

  test-end-to-end:
    machine: true
    working_directory: ~/grakn
    steps:
      - checkout
      - bazel_install
      - bazel_add_rbe_credential
      - bazel:
          command: bazel build //:distribution
      - bazel:
          command: bazel test //test-end-to-end:test-end-to-end --test_output=streamed --spawn_strategy=standalone

  docs-update-grakn-dependency-on-dev-branch:
    machine: true
    steps:
      - checkout
      - run:
          name: Make docs (development branch) depend on the latest Grakn (master)
          command: |
            mkdir docs
            cd docs
            python ../.circleci/docs-update-grakn-dependency-on-dev-branch.py
  
  approve-release:
    machine: true
    steps:
      - checkout
      - run: python .circleci/approve-release.py

  release-cleanup:
    machine: true
    steps:
      - checkout
      - run: git push --delete origin trigger-ci-release

  publish-github-draft:
    machine: true
    working_directory: ~/grakn
    steps:
      - checkout
      - bazel_install
      - bazel_add_rbe_credential
      - run: bazel run //:deploy-github-zip -- ${GRABL_CREDENTIAL}

  docs-auto-merge-to-master:
    machine: true
    steps:
      - checkout
      - run: |
          mkdir docs
          cd docs
          python ../.circleci/docs-auto-merge-to-master.py

  deploy-docs:
    machine: true
    steps:
      - checkout
      - run: |
          mkdir docs
          cd docs
          python ../.circleci/deploy-docs.py

workflows:
  # the 'ci' workflow consists of:
  #  - test jobs (executed on pull requests and master)
  #  - a sync docs jobs (executed on master only)
  #  - a release approval prompt (executed on master only)
  ci:
    jobs:
      # test jobs (executed on pull requests and master)
      - build:
          filters:
            branches:
              ignore: trigger-ci-release
      - client-java:
          filters:
            branches:
              ignore: trigger-ci-release
      - common:
          filters:
            branches:
              ignore: trigger-ci-release
      - console:
          filters:
            branches:
              ignore: trigger-ci-release
      - graql:
          filters:
            branches:
              ignore: trigger-ci-release
      - server:
          filters:
            branches:
              ignore: trigger-ci-release
      - test-integration:
          filters:
            branches:
              ignore: trigger-ci-release
      - test-integration-reasoner:
          filters:
            branches:
              ignore: trigger-ci-release
      - test-integration-analytics:
          filters:
            branches:
              ignore: trigger-ci-release
      - test-end-to-end:
          filters:
            branches:
              ignore: trigger-ci-release

      # sync docs (executed on master only) #
      - docs-update-grakn-dependency-on-dev-branch:
          filters:
            branches:
              only: master
          requires:
            - build
            - client-java
            - common
            - console
            - graql
            - server
            - test-integration
            - test-integration-reasoner
            - test-integration-analytics
            - test-end-to-end

      # approve release (executed on master only)
      # triggers 'ci-release' workflow by creating a branch 'trigger-ci-release' in graknlabs/grakn
      - approve-release:
          filters:
            branches:
              only: master
          requires:
            - docs-update-grakn-dependency-on-dev-branch

  # the 'ci-release' workflow is triggered by the creation of 'trigger-ci-release' branch in graknlabs/grakn
  # it consists of:
  # - releasing Grakn to Github
  # - releasing docs: creating a pull request to docs/master and deploying it to Heroku
  # - cleaning up the 'trigger-ci-release' branch
  ci-release:
    jobs:
      # release (executed on trigger-ci-release only)
      - publish-github-draft:
          filters:
            branches:
              only: trigger-ci-release
      - docs-auto-merge-to-master:
          filters:
            branches:
              only: trigger-ci-release
          requires:
            - publish-github-draft
      - approve-deploy-docs:
          filters:
            branches:
              only: trigger-ci-release
          type: approval
          requires:
            - docs-auto-merge-to-master
      - deploy-docs:
          filters:
            branches:
              only: trigger-ci-release
          requires:
            - approve-deploy-docs
      - release-cleanup:
          requires:
            - deploy-docs
          filters:
            branches:
              only: trigger-ci-release
