# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: picoded/ubuntu-openjdk-8-jdk:latest

    working_directory: ~/repo

    environment:
      MAVEN_OPTS: -Xmx2G -XX:+HeapDumpOnOutOfMemoryError
    
    steps:
      - checkout

      # add necessary 3rd party apt repositories
      - run: curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
      - run: curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
      - run: echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
      - run: sudo apt-get install apt-transport-https
      - run: sudo apt-get update

      # install dependencies
      - run: sudo apt-get install -y nodejs
      - run: sudo apt-get -y install yarn
      - run: sudo apt-get -y install maven

      # build grakn
      - run: mvn versions:set -DnewVersion=test -DgenerateBackupPoms=false
      - run: mvn --batch-mode install -T 2.5C -DskipTests=true
        
      # run tests!
      - run: mvn verify -pl :test-distribution -Dtest="ai.grakn.distribution.**"
      - run: mvn clean verify -P janus -U -Djetty.log.level=WARNING -Djetty.log.appender=STDOUT -DMaven.test.failure.ignore=true -Dsurefire.rerunFailingTestsCount=1

      # make and store reports
      - run:
          name: Save test results
          command: |
            mkdir -p ~/grakn-surefire-reports/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/grakn-surefire-reports/ \;
          when: always
      - store_artifacts:
          path: ~/grakn-surefire-reports/
      - store_test_results:
          path: ~/grakn-surefire-reports/