swagger: '2.0'
info:
  title: Grakn
  description: 'API for clients to interact with Grakn'
  version: "0.1"
schemes: [http]
host: localhost:4567
paths:
  /:
    get:
      summary: Root
      tags: [Root]
      produces: [application/json]
      responses:
        200:
          description: ''
          schema:
            $ref: '#/definitions/Root'
  /kb:
    get:
      summary: Get Knowledge Bases
      tags: [Keyspaces]
      produces: [application/json]
      responses:
        200:
          description: ''
          schema:
            $ref: '#/definitions/KnowledgeBases'
  /kb/{keyspace}:
    parameters:
      - $ref: '#/parameters/keyspace'
    get:
      summary: Get Knowledge Base
      tags: [Keyspaces]
      produces: [application/json]
      responses:
        200:
          description: ''
          schema:
            $ref: '#/definitions/KnowledgeBase'
        404:
          description: ''
    put:
      summary: Put Knowledge Base
      description: >-
        If the keyspace exists, nothing happens. The configuration is returned. This response is the same as the
        response from `/kb/configuration`.
      tags: [Keyspaces]
      produces: [application/json]
      responses:
        200:
          description: ''
          schema:
            $ref: '#/definitions/Configuration'
    delete:
      summary: Delete Knowledge Base
      description: >-
        If the keyspace doesn't exist, nothing happens.
      tags: [Keyspaces]
      responses:
        204:
          description: ''
  /kb/{keyspace}/graql:
    post:
      summary: Execute Graql Query
      tags: [Keyspaces]
      parameters:
      - $ref: '#/parameters/keyspace'
      - name: infer
        in: query
        description: Enable inference
        type: boolean
      - name: limitEmbedded
        in: query
        description: Number of embedded concepts to return
        type: number
      - name: defineAllVars
        in: query
        description: Define all anonymous variables in the query
        type: boolean
      - name: multi
        in: query
        description: Support multiple queries
        type: boolean
      - name: explain
        in: query
        description: Provide an explanation of how results were inferred
        type: boolean
      - name: body
        in: body
        schema:
          $ref: '#/definitions/GraqlQuery'
        required: true
      produces: [text/plain, application/json]
      responses:
        200:
          description: ''
          schema:
            $ref: '#/definitions/GraqlResponse'
        400:
          description: ''
  /kb/{keyspace}/concept/{id}:
    get:
      summary: Get Concept
      tags: [Concepts]
      parameters:
      - $ref: '#/parameters/keyspace'
      - name: id
        in: path
        required: true
        type: string
        x-example: V123
#       For OpenAPI 3.0
#       schema:
#         $ref: '#/definitions/ConceptID'
      produces: [application/json]
      responses:
        200:
          description: ''
          schema:
            $ref: '#/definitions/Concept'
        404:
          description: ''
  /kb/{keyspace}/type:
    get:
      summary: Get Types
      tags: [Concepts]
      parameters:
      - $ref: '#/parameters/keyspace'
      produces: [application/json]
      responses:
        200:
          description: ''
          schema:
            $ref: '#/definitions/Types'
  /kb/{keyspace}/type/{label}:
    get:
      summary: Get Type
      tags: [Concepts]
      parameters:
      - $ref: '#/parameters/keyspace'
      - $ref: '#/parameters/label'
      produces: [application/json]
      responses:
        200:
          description: ''
          schema:
            $ref: '#/definitions/Type'
        404:
          description: ''
  /kb/{keyspace}/type/{label}/instance:
    get:
      summary: Get Instances
      tags: [Concepts]
      parameters:
      - $ref: '#/parameters/keyspace'
      - $ref: '#/parameters/label'
      - name: limit
        in: query
        type: number
      - name: offset
        in: query
        type: number
      produces: [application/json]
      responses:
        200:
          description: ''
          schema:
            $ref: '#/definitions/Instances'
        404:
          description: ''
  /kb/{keyspace}/role:
    get:
      summary: Get Roles
      tags: [Concepts]
      parameters:
      - $ref: '#/parameters/keyspace'
      produces: [application/json]
      responses:
        200:
          description: ''
          schema:
            $ref: '#/definitions/Roles'
  /kb/{keyspace}/role/{label}:
    get:
      summary: Get Role
      tags: [Concepts]
      parameters:
      - $ref: '#/parameters/keyspace'
      - $ref: '#/parameters/label'
      produces: [application/json]
      responses:
        200:
          description: ''
          schema:
            $ref: '#/definitions/Role'
        404:
          description: ''
  /kb/{keyspace}/rule:
    get:
      summary: Get Rules
      tags: [Concepts]
      parameters:
      - $ref: '#/parameters/keyspace'
      produces: [application/json]
      responses:
        200:
          description: ''
          schema:
            $ref: '#/definitions/Rules'
  /kb/{keyspace}/rule/{label}:
    get:
      summary: Get Rule
      tags: [Concepts]
      parameters:
      - $ref: '#/parameters/keyspace'
      - $ref: '#/parameters/label'
      produces: [application/json]
      responses:
        200:
          description: ''
          schema:
            $ref: '#/definitions/Rule'
        404:
          description: ''
  /configuration:
    get:
      summary: Get Configuration
      tags: [Internal]
      produces: [application/json]
      responses:
        200:
          description: ''
          schema:
            $ref: '#/definitions/Configuration'
  /status:
    get:
      summary: Get Status
      tags: [Internal]
      produces: [application/json]
      responses:
        200:
          description: ''
          schema:
            $ref: '#/definitions/StatusResponse'
  /metrics:
    get:
      summary: Get Metrics
      tags: [Internal]
      produces: [text/plain]
      responses:
        200:
          description: ''
          schema:
            type: object
  /kb/{keyspace}/commit_log:
    post:
      summary: Post Commit Log
      tags: [Internal]
      parameters:
      - $ref: '#/parameters/keyspace'
      - name: body
        in: body
        schema:
          $ref: '#/definitions/CommitLogRequest'
        required: true
      produces: [application/json]
      responses:
        200:
          description: ''
          schema:
            $ref: '#/definitions/CommitLogResponse'
  /task:
    get:
      summary: Get Tasks
      tags: [Internal]
      produces: [text/plain]
      responses:
        200:
          description: ''
          schema:
            $ref: '#/definitions/Tasks'
    post:
      summary: Post Tasks
      tags: [Internal]
      responses:
        201:
          description: ''
  /task/{id}:
    get:
      summary: Get Task
      tags: [Internal]
      parameters:
      - name: id
        in: path
        required: true
        type: string
        x-example: '8e7c91a9-ff3c-4df9-86ee-da2e76ce1482'
#       For OpenAPI 3.0
#       schema:
#         $ref: '#/definitions/TaskId'
      produces: [text/plain]
      responses:
        200:
          description: ''
          schema:
            $ref: '#/definitions/Task'
  /task/{id}/stop:
    put:
      summary: Stop Task
      tags: [Internal]
      parameters:
      - name: id
        in: path
        required: true
        type: string
        x-example: '8e7c91a9-ff3c-4df9-86ee-da2e76ce1482'
#       For OpenAPI 3.0
#       schema:
#         $ref: '#/definitions/TaskId'
      responses:
        204:
          description: ''
parameters:
  keyspace:
    name: keyspace
    in: path
    required: true
    type: string
    x-example: genealogy
#   For OpenAPI 3.0
#   schema:
#     $ref: '#/definitions/Keyspace'
  label:
    name: label
    in: path
    required: true
    type: string
    x-example: person
#   For OpenAPI 3.0
#   schema:
#     $ref: '#/definitions/Label'
definitions:
  Root:
    type: object
    required: [keyspaces]
    properties:
      keyspaces:
        $ref: '#/definitions/KnowledgeBasesLink'
  KnowledgeBasesLink:
    type: string
    format: uri
    example: /kb
  KnowledgeBases:
    type: object
    required: ['@id', keyspaces, keyspace]
    properties:
      '@id':
        $ref: '#/definitions/KnowledgeBasesLink'
      keyspaces:
        type: array
        items:
          $ref: '#/definitions/KnowledgeBase'
      keyspace:
        type: string
        format: uri
        example: /kb/{keyspace}
  Keyspace:
    type: string
    example: genealogy
  KnowledgeBase:
    required: ['@id', name, types, roles, rules, graql]
    type: object
    properties:
      '@id':
        type: string
        example: /kb/genealogy
      name:
        $ref: '#/definitions/Keyspace'
      types:
        $ref: '#/definitions/TypesLink'
      roles:
        $ref: '#/definitions/RolesLink'
      rules:
        $ref: '#/definitions/RulesLink'
      graql:
        type: string
        format: uri
        example: /kb/genealogy/graql
  Label:
    type: string
    example: person
  ConceptLink:
    type: string
    format: uri
    example: /kb/genealogy/concept/V123
  Concept:
    $ref: '#/definitions/Thing'
#   For OpenAPI 3.0
#   oneOf:
#     - $ref: '#/definitions/Thing'
#     - $ref: '#/definitions/Type'
#     - $ref: '#/definitions/Role'
#     - $ref: '#/definitions/Rule'
#   example:
#     '@id': /kb/genealogy/concept/V123
#     type:
#       '@id': /kb/genealogy/type/person
#       label: person
#     relationships:
#     - role: /kb/genealogy/role/husband
#       relationship: /kb/genealogy/concept/V456
#     attributes:
#     - '@id': /kb/genealogy/concept/V321
#       type:
#         '@id': /kb/genealogy/type/name
#         label: name
#        value: 'Bob'
#     keys:
#     - '@id': /kb/genealogy/concept/V654
#       type:
#         '@id': /kb/genealogy/type/person-id
#         label: person-id
#       value: 808
  Thing:
    required: ['@id', type, relationships, attributes, keys]
    type: object
    properties:
      '@id':
        $ref: '#/definitions/ConceptLink'
      type:
        $ref: '#/definitions/TypeSummary'
      relationships:
        type: array
        items:
          $ref: '#/definitions/Relationships'
      attributes:
        type: array
        items:
          $ref: '#/definitions/AttributeSummary'
      keys:
        type: array
        items:
          $ref: '#/definitions/AttributeSummary'
      rolePlayers:
        type: array
        items:
          $ref: '#/definitions/RolePlayers'
      value:
        $ref: '#/definitions/Value'
  Relationships:
    required: [role, relationship]
    type: object
    properties:
      role:
        $ref: '#/definitions/RoleLink'
      relationship:
        $ref: '#/definitions/ConceptLink'
  RolePlayers:
    required: [role, player]
    type: object
    properties:
      role:
        $ref: '#/definitions/RoleLink'
      player:
        $ref: '#/definitions/ConceptLink'
  AttributeSummary:
    type: object
    required: ['@id', type, value]
    properties:
      '@id':
        $ref: '#/definitions/ConceptLink'
      type:
        $ref: '#/definitions/TypeSummary'
      value:
        $ref: '#/definitions/Value'
  Value:
    {}
#   For OpenAPI 3.0
#   anyOf:
#     - type: string
#     - type: number
#     - type: boolean
  TypesLink:
    type: string
    format: uri
    example: /kb/genealogy/type
  Types:
    type: object
    required: ['@id', types]
    properties:
      '@id':
        $ref: '#/definitions/Types'
      types:
        type: array
        items:
          $ref: '#/definitions/Type'
  TypeLink:
    type: string
    format: uri
    example: /kb/genealogy/type/person
  TypeSummary:
    required: ['@id', label]
    type: object
    properties:
      '@id':
        $ref: '#/definitions/TypeLink'
      label:
        $ref: '#/definitions/Label'
  Type:
    allOf:
      - $ref: '#/definitions/TypeSummary'
    required: [abstract, implicit, plays, attributes, keys, subs]
    type: object
    properties:
      abstract:
        type: boolean
      implicit:
        type: boolean
      plays:
        type: array
        items:
          $ref: '#/definitions/RoleLink'
      attributes:
        type: array
        items:
          $ref: '#/definitions/TypeLink'
      keys:
        type: array
        items:
          $ref: '#/definitions/TypeLink'
      subs:
        type: array
        items:
          $ref: '#/definitions/TypeLink'
      relates:
        type: array
        items:
          $ref: '#/definitions/RoleLink'
      super:
        allOf: [$ref: '#/definitions/TypeLink']
        example: /kb/genealogy/type/entity
      instances:
        $ref: '#/definitions/InstancesLink'
  InstancesLink:
    type: string
    format: uri
    example: /kb/genealogy/type/person/instance
  Instances:
    required: ['@id', concepts]
    type: object
    properties:
      '@id':
        allOf: [$ref: '#/definitions/InstancesLink']
        example: /kb/genealogy/type/person/instance?limit=100&offset=100
      concepts:
        type: array
        items:
          $ref: '#/definitions/Concept'
      next:
        allOf: [$ref: '#/definitions/InstancesLink']
        example: /kb/genealogy/type/person/instance?limit=100&offset=200
      previous:
        allOf: [$ref: '#/definitions/InstancesLink']
        example: /kb/genealogy/type/person/instance?limit=100&offset=0
  RoleLink:
    type: string
    format: uri
    example: /kb/genealogy/role/husband
  RoleSummary:
    required: ['@id', label, relationships]
    type: object
    properties:
      '@id':
        $ref: '#/definitions/RoleLink'
      label:
        allOf: [$ref: '#/definitions/Label']
        example: husband
      relationships:
        type: array
        items:
          $ref: '#/definitions/TypeLink'
  RolesLink:
    type: string
    format: uri
    example: /kb/genealogy/role
  Roles:
    type: object
    required: ['@id', roles]
    properties:
      '@id':
        $ref: '#/definitions/RolesLink'
      roles:
        type: array
        items:
          $ref: '#/definitions/Role'
  Role:
    allOf:
      - $ref: '#/definitions/RoleSummary'
    required: [implicit, rolePlayers, subs]
    type: object
    properties:
      implicit:
        type: boolean
      rolePlayers:
        type: array
        items:
          allOf: [$ref: '#/definitions/TypeLink']
          example: /kb/genealogy/type/marriage
      subs:
        type: array
        items:
          allOf: [$ref: '#/definitions/RoleLink']
          example: /kb/genealogy/role/husband
      super:
        allOf: [$ref: '#/definitions/RoleLink']
        example: /kb/genealogy/role/spouse
  RuleLink:
    type: string
    format: uri
    example: /kb/genealogy/rule/grandparent-rule
  RulesLink:
    type: string
    format: uri
    example: /kb/genealogy/rule
  Rules:
    type: object
    required: ['@id', rules]
    properties:
      '@id':
        $ref: '#/definitions/RulesLink'
      rules:
        type: array
        items:
          $ref: '#/definitions/Rule'
  Rule:
    type: object
    properties:
      '@id':
        $ref: '#/definitions/RuleLink'
      implicit:
        type: boolean
      subs:
        type: array
        items:
          $ref: '#/definitions/RuleLink'
      super:
        allOf: [$ref: '#/definitions/RuleLink']
        example: /kb/genealogy/rule/rule
      label:
        allOf: [$ref: '#/definitions/Label']
        example: grandparent-rule
      when:
        type: string
        example: '(parent: $x, child: $y); (parent: $y, child: $z);'
      then:
        type: string
        example: '(grandparent: $x, grandchild: $y) isa grandparentship;'
  Answer:
    type: object
    additionalProperties:
      $ref: '#/definitions/Concept'
  Configuration:
    type: object
#   For OpenAPI 3.0
#   additionalProperties:
#     oneOf:
#       - type: string
#       - type: number
#       - type: boolean
    example:
      knowledge-base.mode: production
      knowledge-base.analytics: distributed
      knowledge-base.default-keyspace: grakn
      knowledge-base.sharding-threshold: 10000
      knowledge-base.schema-cache-timeout-ms: 600000
      server.host: 0.0.0.0
      server.port: 4567
      server.static-file-dir: ../services/assets/
      loader.repeat-commits: 5
      tasks.postprocessing.delay: 60000
      loader.threads: 4
      webserver.threads: 64
      log.dirs: ../logs/
      log.level: INFO
      storage.backend: grakn-production
      storage.hostname: 127.0.0.1
      cache.db-cache: true
      cache.db-cache-clean-wait: 20
      cache.db-cache-time: 180000
      cache.db-cache-size: 0.25
      queue.host: localhost:6379
      queue.consumers: 32
      redis.pool-size: 32
  StatusResponse:
    type: object
    properties:
      status:
        type: string
        enum:
          - READY
          - INITIALIZING
  CommitLogRequest:
    required:
    - types-with-new-counts
    - concepts-to-fix
    type: object
    properties:
      types-with-new-counts:
        type: array
        items:
          $ref: '#/definitions/TypesWithNewCounts'
      concepts-to-fix:
        $ref: '#/definitions/ConceptsToFix'
  TypesWithNewCounts:
    type: object
    required: [concept-id, sharding-count]
    properties:
      concept-id:
        $ref: '#/definitions/ConceptID'
      sharding-count:
        type: number
  ConceptsToFix:
    type: object
    additionalProperties:
      type: object
      additionalProperties:
        type: array
        items:
          $ref: '#/definitions/ConceptID'
    example:
      ATTRIBUTE:
        ATTRIBUTE-name-Bob: [V123, V456, V789]
  ConceptID:
    type: string
    example: V123
  CommitLogResponse:
      $ref: '#/definitions/Task'
  Tasks:
    type: object
    required: ['@id', tasks]
    properties:
      '@id':
        type: string
        format: uri
        example: '/task'
      tasks:
        type: array
        items:
          $ref: '#/definitions/Task'
  Task:
    type: object
    properties:
      '@id':
        type: string
        format: uri
        example: '/task/8e7c91a9-ff3c-4df9-86ee-da2e76ce1482'
      id:
        $ref: '#/definitions/TaskId'
      creator:
        type: string
        example: 'ai.grakn.engine.postprocessing.PostProcessingTask'
      schedule:
        type: object
        properties:
          runAt:
            type: number
            example: 1511205030
          interval:
            type: number
            example: 120
      serialVersionUID:
        type: number
        example: -7301340972479426653
      priority:
        type: string
        enum: [LOW, HIGH]
      status:
        type: string
        enum: [CREATED, SCHEDULED, RUNNING, COMPLETED, STOPPED, FAILED]
      taskClassName:
        type: string
        example: 'ai.grakn.engine.postprocessing.PostProcessingTask'
      engineId:
        type: string
        example: '8e7c91a9-ff3c-4df9-86ee-da2e76ce1482'
      taskCheckpoint:
        type: object
  TaskId:
    type: string
    example: '8e7c91a9-ff3c-4df9-86ee-da2e76ce1482'
  GraqlQuery:
    type: string
    example: 'match $x isa person; get;'
  GraqlResponse:
    type: array
    items:
      $ref: '#/definitions/Answer'
